### ISSUE TITLE
Set scopes as nonMandatory property of a security definition

### ISSUE THREAD

**Issue by tgrzywacz** [apiaddicts/sonar-openapi#1]
Hi it seems that scanner requires scopes for each and single element of securityDefinitions. This is a bit problematic for us, as some of our internal definitions may not necessarily contain any  scopes. Also I believe it is not invalid from openAPI specification point of view. 
Do you think it would be possible to make a change and set it from:
      b.mandatoryProperty("scopes", b.object(
into:
      b.**property**("scopes", b.object(

inside OpenApi2/3Grammar

**Comment by EnriqueGomez12** [comment]
Hi!

Thank you for bringing this to our attention. We have reviewed the issue and you are correct.

We have already made the necessary change.
